stages:
  - build
  - compile

build:
  stage: build
  image: node:20
  before_script:
    - npm config set registry https://registry.npmmirror.com
    - corepack enable
    - corepack prepare pnpm@latest --activate
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm install # install dependencies
    - pnpm build # build the project
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
  artifacts:
    paths:
      - dist/

compile:
  stage: compile
  dependencies:
    - build
  image:
    name: denoland/deno:alpine
    entrypoint: [""]
  script:
    - deno task compile
  artifacts:
    paths:
    - dist/
